import { Layers3 } from 'lucide-react'
import { HoverCard, HoverCardContent, HoverCardTrigger } from '@/components/ui/hover-card'
import { Button } from '@/components/ui/button'
import type { GraphiteStack } from '../../../../shared/github/graphite-stack'
import type { WorktreeCardPrDisplay } from './worktree-card-pr-display'
import {
  WorktreeCardDetailSection,
  WorktreeCardDetailSectionContent
} from './WorktreeCardDetailSection'
import { DetailHeader } from './WorktreeCardMetadataControls'

function stackForReview(review: WorktreeCardPrDisplay | null): GraphiteStack | null {
  if (!review || review.provider !== 'github' || !('graphiteStack' in review)) {
    return null
  }
  const stack = review.graphiteStack
  return stack &&
    stack.entries.length > 1 &&
    stack.entries.some((entry) => entry.number === review.number)
    ? stack
    : null
}

export function GraphiteStackDetails({ review }: { review: WorktreeCardPrDisplay | null }) {
  const stack = stackForReview(review)
  if (!stack || !review) {
    return null
  }
  return (
    <WorktreeCardDetailSection>
      <DetailHeader
        icon={<Layers3 className="size-3" />}
        label={`Graphite stack · ${stack.entries.length} PRs`}
      />
      <WorktreeCardDetailSectionContent>
        {stack.stale && (
          <p className="text-xs text-muted-foreground">
            Last known stack; refresh is temporarily unavailable.
          </p>
        )}
        <div
          className="scrollbar-sleek max-h-64 space-y-1 overflow-y-auto"
          data-graphite-stack-list=""
        >
          {stack.entries.map((entry) => (
            <Button
              key={entry.number}
              variant={entry.number === review.number ? 'secondary' : 'ghost'}
              size="xs"
              className="h-auto w-full justify-start whitespace-normal text-left"
              data-graphite-stack-pr={entry.number}
              aria-current={entry.number === review.number ? 'true' : undefined}
              onClick={(event) => {
                event.stopPropagation()
                // The destination is generated by the host; refuse unrelated schemes/origins from old cache data.
                let url: URL
                try {
                  url = new URL(entry.url)
                } catch {
                  return
                }
                if (
                  url.protocol === 'https:' &&
                  url.hostname === 'app.graphite.com' &&
                  !url.username &&
                  !url.password
                ) {
                  void window.api.shell.openUrl(url.href)
                }
              }}
            >
              <span className="shrink-0 tabular-nums">#{entry.number}</span>
              <span className="min-w-0 flex-1 break-words">
                {entry.title ?? 'Title unavailable'}
              </span>
              {entry.number === review.number && (
                <span className="shrink-0 text-xs text-muted-foreground">This PR</span>
              )}
            </Button>
          ))}
        </div>
      </WorktreeCardDetailSectionContent>
    </WorktreeCardDetailSection>
  )
}

export function GraphiteStackBadge({
  review,
  ownHover = true
}: {
  review: WorktreeCardPrDisplay | null
  ownHover?: boolean
}) {
  const stack = stackForReview(review)
  if (!stack) {
    return null
  }
  if (!ownHover) {
    return (
      <span
        role="img"
        aria-label={`Graphite stack: ${stack.entries.length} PRs`}
        data-worktree-stack-icon=""
        className="inline-flex shrink-0 items-center text-muted-foreground"
      >
        <Layers3 className="size-3.5" />
      </span>
    )
  }
  return (
    <HoverCard openDelay={250} closeDelay={150}>
      <HoverCardTrigger asChild>
        <span
          tabIndex={0}
          role="img"
          aria-label={`Graphite stack: ${stack.entries.length} PRs`}
          data-worktree-stack-icon=""
          className="inline-flex shrink-0 items-center text-muted-foreground"
          onPointerDown={(event) => event.stopPropagation()}
          onClick={(event) => event.stopPropagation()}
        >
          <Layers3 className="size-3.5" />
        </span>
      </HoverCardTrigger>
      <HoverCardContent
        side="right"
        align="start"
        className="w-96 max-w-[calc(100vw-2rem)]"
        onClick={(event) => event.stopPropagation()}
      >
        <GraphiteStackDetails review={review} />
      </HoverCardContent>
    </HoverCard>
  )
}
